blank_issues_enabled: true
contact_links:
  - name: OceanBase Forum(Chinese)
    url: https://ask.oceanbase.com
    about: Please ask and answer questions in our forum.
  - name: OceanBase Slack
    url: https://join.slack.com/t/oceanbase/shared_invite/zt-1e25oz3ol-lJ6YNqPHaKwY_mhhioyEuw
    about: Ask questions in our user group.
