name: 🌟 Enhancement
description: I want an enhancement for this project
title: "[Enhancement]: "
labels: ["type: enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this issue is encountered for the first time.
        
        Thank you very much for your feedback!
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description.
    validations:
      required: true
  - type: markdown
    attributes:
      value: Thanks for completing our form!
